name: Container
on: workflow_dispatch

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:alpine
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
